import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ReduxProvider from "./providers/ReduxProvider";
import { Toaster } from "sonner";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Food Order App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <ReduxProvider>
          <Header />
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              style: {
                color: "var(--primary)",
                fontWeight: "bold",
                fontSize: "16px",
                borderRadius: "12px",
              },
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
